source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins
gem "jekyll-paginate", "~> 1.1", group: :jekyll_plugins
  gem "jekyll-sitemap", group: :jekyll_plugins
  gem "jekyll-gist", group: :jekyll_plugins
  #gem "jekyll-feed", group: :jekyll_plugins
  gem "jemoji", group: :jekyll_plugins
  #gem "jekyll-include-cache", group: :jekyll_plugins
  gem "jekyll-algolia", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
  gem "jekyll-algolia"
end
